### ISSUE TITLE
Uncaught error when resizing read view

### ISSUE THREAD

**Issue by buckley-w-david** [zwzn/comicbox#8]
```Uncaught TypeError: Cannot read property 'width' of null```

https://github.com/zwzn/comicbox/blob/1e9c1f8680911cdd965b9fea0ab211507e23f29e/web/src/js/views/read.tsx#L167-L170

This is because the `adjustAreaRegions` method does a check for `this.img === undefined`, meaning `null` sneaks by.

**Comment by zwzn** [comment]
This was fixed by #19. It no longer checks the size of the image
